### PR TITLE
update-2020-09-25

### PR DESCRIPTION
**Pull request by kba**
This PR supersedes #196 and includes fixes for the getLogger CRITICAL log messages that have been fixed in most modules yesterday.

### CODE REVIEW

**Review by stweil — APPROVED** [review]
Works for me. There remain error messages for `ocrd_cis` which can be ignored when running an OCR-D process.

**Comment by kba** [comment]
> Works for me. There remain error messages for ocrd_cis which can be ignored when running an OCR-D process.

What error messages?

**Comment by stweil** [comment]
I get the same errors from `getLogger` as before:

    14:50:19.563 CRITICAL root - getLogger was called before initLogging. Source of the call:
    14:50:19.564 CRITICAL root -   File "/venv-20200925/lib/python3.7/site-packages/ocrd_cis/ocropy/common.py", line 19, in <module>
    14:50:19.564 CRITICAL root -     LOG = getLogger('ocrolib') # to be refined by importer

**Comment by kba** [comment]
> I get the same errors from `getLogger` as before:
> 
> ```
> 14:50:19.563 CRITICAL root - getLogger was called before initLogging. Source of the call:
> 14:50:19.564 CRITICAL root -   File "/venv-20200925/lib/python3.7/site-packages/ocrd_cis/ocropy/common.py", line 19, in <module>
> 14:50:19.564 CRITICAL root -     LOG = getLogger('ocrolib') # to be refined by importer
> ```

That would have been easy to fix for this release.

**Comment by bertsky** [comment]
> > ```
> > 14:50:19.564 CRITICAL root -     LOG = getLogger('ocrolib') # to be refined by importer
> > ```
> 
> 
> That would have been easy to fix for this release.

Sorry, that one slipped through.

**Comment by stweil** [comment]
I am sure more releases will follow, so enough opportunities for fixing remaining issues.

**Comment by stweil** [comment]
@bertsky, @kba, is somebody working on an update for ocrd_cis? I still get that error message.

**Comment by bertsky** [comment]
> is somebody working on an update for ocrd_cis? I still get that error message.

https://github.com/cisocrgroup/ocrd_cis/pull/71

**Pull request merged**
