### PR TITLE
Use qualified names for Docker images

### PR DESCRIPTION
**Pull request by stweil**
This allows using podman instead of docker.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by bertsky** [comment]
> This allows using podman instead of docker.

Interesting. Could you elaborate on that? (Here or in the README)

**Comment by stweil** [comment]
Podman is a drop-in replacement for Docker and included in Debian / Ubuntu. The main difference is that it does not need a daemon and also can be run rootless. By default it does not assume that an image comes from docker.io. Using a qualified name tells it where those images come from (and also works with the normal Docker).

**Comment by bertsky** [comment]
I did not know that Podman is directly compatible with Docker images, and can pull from Drockerhub.

What about GPU usage and `nvidia-docker` daemon?

Linking `podman` to `docker` sounds good: Could you please edit the README to explain that possibility?

**Comment by stweil** [comment]
Before promoting podman it is necessary to test it in the OCR-D context. For example I simply don't know how good it can be used with GPU. Therefore I'd wait with mentioning it in the README.

**Comment by stweil** [comment]
Can I merge this PR?

**Comment by kba** [comment]
>> Before promoting podman it is necessary to test it in the OCR-D context
> Can I merge this PR?

Are we certain that this won't break anything with Docker / DockerHub deployment? I'd feel more comfortable with merging if we had running CI.

**Comment by stweil** [comment]
> > > Before promoting podman it is necessary to test it in the OCR-D context
> > > Can I merge this PR?
> 
> Are we certain that this won't break anything with Docker / DockerHub deployment? I'd feel more comfortable with merging if we had running CI.

The change is only used in `Dockerfile`. Building a local Docker image is sufficient for a test.

**Comment by stweil** [comment]
See https://github.com/stweil/ocrd_all/runs/5758316217 which shows that the patch does not break the Docker image build.

**Comment by bertsky** [comment]
It's like a default namespace. Even without it, you can see docker.io top level when pushing or pulling against DH.

**Review by bertsky — APPROVED** [review]

**Comment by bertsky** [comment]
> Can I merge this PR?

I suggest placing the merge and release cycle in one hand whenever possible. That would be @kba. See [here](https://github.com/OCR-D/ocrd_all/pull/309#issuecomment-1083258001)

**Comment by kba** [comment]
Sry, this should have been part of the release, will fix right away.

**Pull request merged**
