### PR TITLE
Docker build staged

### LINKED ISSUE #416: Docker: interference with older versions of core
We build Docker by setting `ocrd/core:$CORE_VERSION` as base stage, with `CORE_VERSION` being the ref currently checked in as submodule. That's not ideal, since we then `make all`, which installs core _again_, this time as editable install with `/build/core` as source location, so both installations will be mixed (so derived stages cannot simply update core again).

Since in core 2.61.0 the distribution changed from ocrd + ocrd_utils + ocrd_models etc to just ocrd, but as a workaround to not break things it was decided to still ship the other packages as aliases, now all of the other packages have to be _uninstalled_ before proceeding.

(This is why #412 is still broken in Docker despite #415 installing the fixes for https://github.com/OCR-D/core/issues/1195.)

### LINKED ISSUE #417: Docker: build CD images sequentially
Currently we build minimum, medium, maximum and maximum-cuda in parallel.

Except for the latter, this offers no time advantage, just consumes more resources (credits).

I suggest we change to
- medium using minimum as first stage
- maximum using medium as first stage

and have the respective jobs depend on each other in the CI.

### LINKED ISSUE #427: `make check` fails since January
`ocrd_froc` is broken since two months (see https://github.com/OCR-D/ocrd_froc/issues/10).

### LINKED ISSUE #434: Broken build (ocrd_detectron2)
See https://github.com/bertsky/ocrd_detectron2/issues/29 for details. It is broken with any Python version.

### PR DESCRIPTION
**Pull request by bertsky**
fixes #416 
fixes #417 
fixes #434 
fixes #427

### CODE REVIEW

**Comment by bertsky** [comment]
Does anyone know why CircleCI (again) does not get triggered?

**Comment by bertsky** [comment]
> Please create separate pull requests for the commits that are not related to the staged Docker build. Some commits are easy to review and could be merged fast, but 11 commits in a single pull request makes it much more difficult to review, at least for me.
> 
> It would also be good to update ocrd_tesserocr with the latest Tesseract which includes several important improvements. Currently it uses a two months old release.

That's an unreasonable demand. We had no release for a long time, CI did not work for multiple reasons. This is the first attempt to get a workable ocrd_all again – I _have to_ combine multiple changes, otherwise it would be without merit.

**Comment by stweil** [comment]
> I _have to_ combine multiple changes, otherwise it would be without merit.

Then good luck. I won't be able to review this pull request further.

**Comment by bertsky** [comment]
I triggered CI manually on my fork:
- [x] [Github Actions](https://github.com/bertsky/ocrd_all/actions/runs/9230738358/job/25399477087)
- [x] [CircleCI](https://app.circleci.com/pipelines/github/bertsky/ocrd_all/64/workflows/9cdc6d72-525d-45a2-925c-d68e2915a734/jobs/70)

**Pull request merged**
