### PR TITLE
Disable modules which require old tensorflow-gpu unless it is available

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Review by kba — APPROVED** [review]
Fine by me, but let's make sure @bertsky is on board since these are his projects.

**Comment by stweil** [comment]
@bertsky. do you have any comments? Can I merge this pull request?

**Comment by stweil** [comment]
Ping?

**Review by bertsky — APPROVED** [review]
So be it.

(I hope we can delegate to module-containers soon, anyway.)

**Pull request merged**
