### PR TITLE
synchronize concurrent git submodule actions via mutex

### LINKED ISSUE #123: avoid race for git lockfile when syncing modules in parallel
There's a race condition for the `.git/config.lock` file between parallel jobs when they want to synchronize / update some submodules. It must have been around for some time already, and only surfaces when using `make -j N` (i.e. with some fixed number of jobs), but not `make -j` (i.e. relative to the current system load-level).

_Originally posted by @bertsky in https://github.com/OCR-D/ocrd_all/pull/121_

### PR DESCRIPTION
**Pull request by bertsky**
Fixes #123 

@stweil please test this, too!

### CODE REVIEW

**Comment by bertsky** [comment]
@kba CI fails because GNU `parallel` is already needed for `deps-ubuntu` now (just like `make` and `git` are needed a priori). Do you think I should add a rule to CircleCI (before `setup_remote_docker`)?

**Comment by kba** [comment]
> Do you think I should add a rule to CircleCI (before setup_remote_docker)?

:+1: That is what I would do. Before/after setup_remote_docker as you please but before `run: make docker-maximum`.

**Comment by bertsky** [comment]
> That is what I would do. Before/after setup_remote_docker as you please but before `run: make docker-maximum`.

Ok, but until the new rule is in place, we won't see whether it works :frowning: 

Alternatively, I could re-organize `deps-ubuntu` such that it first installs all packages for `ocrd_all` itself, and only then goes to look at submodules' `deps-ubuntu`...

**Comment by bertsky** [comment]
> Alternatively, I could re-organize `deps-ubuntu` such that it first installs all packages for `ocrd_all` itself, and only then goes to look at submodules' `deps-ubuntu`...

That worked. Except for `make` itself, everything can be installed via `make deps-ubuntu` now.

**Comment by kba** [comment]
@stweil I cannot reproduce the `git` lock file race condition issue. I notice no overhead from using parallel's `sem` here but does it fix #123 for you?

What I **did** notice was that `make modules` in this branch will not update opencv-python but it does so in master. Any idea why that is?

**Comment by bertsky** [comment]
> What I **did** notice was that `make modules` in this branch will not update opencv-python but it does so in master. Any idea why that is?

In a fresh clone, `opencv-python` is under `DISABLED_MODULES`.

> I cannot reproduce the `git` lock file race condition issue.

Try doing `make -j4 all MODULES="core sbb_textline_detector ocrd_anybaseocr ocrd_tesserocr"` (perhaps repeatedly). You will soon get an `error: could not lock config file .git/config` message with a non-zero retval from make.

**Comment by kba** [comment]
> `make -j4 all MODULES="core sbb_textline_detector ocrd_anybaseocr ocrd_tesserocr"`

That did the trick in master after several tries. Can confirm that with this fix, no more "lock file exists" messages no matter how often I try. Thanks, merging.

**Pull request merged**
