### PR TITLE
Update 2024 10 11

### PR DESCRIPTION
**Pull request by kba**
Time for a new release!

Includes the just released v2.70.0 of OCR-D/core as well as Dockerfiles for most projects (ht @joschrew @bertsky for that effort), so we now have slim containers consistently.

Also includes a new processor `ocrd-page2alto-transform` that provides an OCR-D interface for https://github.com/OCR-D/page-to-alto directly, which is significantly faster than using it via `ocrd-fileformat-transform -P from-to 'page alto'`.

### CODE REVIEW

**Comment by bertsky** [comment]
@kba you can update ocrd_cis from bertsky/fix-alpha-shape now.

But it seems that [page2alto](https://github.com/OCR-D/page-to-alto/tree/8877e8f050df76448ff99bf27f43994b30f894ba) is still broken:
```
0.140 Traceback (most recent call last):
0.140   File "/usr/local/bin/ocrd-page2alto-transform", line 5, in <module>
0.140     from ocrd_page_to_alto.ocrd_cli import main
0.140 ModuleNotFoundError: No module named 'ocrd_page_to_alto.ocrd_cli'
```
This was an editable install, so ...

**Comment by bertsky** [comment]
> This was an editable install, so ...

Could this be interference from the _older_ page-to-alto still packaged under ocrd_fileformat/repo/ocr-fileformat/vendor?

**Comment by kba** [comment]
> > This was an editable install, so ...
> 
> Could this be interference from the _older_ page-to-alto still packaged under ocrd_fileformat/repo/ocr-fileformat/vendor?

Yes, indeed, thanks. Updated.

**Comment by bertsky** [comment]
It won't affect our (fat image) Docker build, but you can update dinglehopper after [this](https://github.com/qurator-spk/dinglehopper/pull/120) once more, @kba.

**Comment by bertsky** [comment]
> It won't affect our (fat image) Docker build, but you can update dinglehopper after [this](https://github.com/qurator-spk/dinglehopper/pull/120) once more, @kba.

We also need https://github.com/qurator-spk/sbb_binarization/pull/70 to avoid the TF conflict between eynollah and sbb_binarization – can you please update, @kba?

**Comment by bertsky** [comment]
circleci-ocrdall

**Comment by bertsky** [comment]
Test upload now also working (CircleCI does not allow directly mounting volumes into Docker containers):
circleci-ocrdall

**Review by bertsky — APPROVED** [review]

**Pull request merged**
