### PR TITLE
:package: v2021-07-19

### PR DESCRIPTION
**Pull request by kba**
Time for another update. This updates core to 2.25.1 and includes various fixes to processors like eynollah, ocrd_cis, cor-asv-ann, ocrd_tesserocr etc.

Also updates tesseract and tesserocr. @stweil let me know if this might lead to problems.

### CODE REVIEW

**Comment by bertsky** [comment]
@kba this fails because it cannot find ocrd_tesserocr c9a27bd263501c32f06009672417b8223bc57836 (which I also don't know). Perhaps you've merged something locally and forgot to push?

Anyway, I think this really should include https://github.com/OCR-D/ocrd_tesserocr/pull/179 (perhaps after merging and re-releasing, I can do that).

But really, before updating we shoud **fix** https://github.com/OCR-D/ocrd_all/pull/264 (i.e. our headless-tf2 sub-venv including Calamari). AFAICS the blocker right now is [ocrd_calamari](https://github.com/OCR-D/ocrd_calamari/commit/2fd6e536f6bf83975ba09353a83e04d75e680535#comments).

**Comment by bertsky** [comment]
> Anyway, I think this really should include [OCR-D/ocrd_tesserocr#179](https://github.com/OCR-D/ocrd_tesserocr/pull/179) (perhaps after merging and re-releasing, I can do that).

Done. I recommend updating to the new ocrd_tesserocr master here.

> But really, before updating we shoud **fix** #264 (i.e. our headless-tf2 sub-venv including Calamari). AFAICS the blocker right now is [ocrd_calamari](https://github.com/OCR-D/ocrd_calamari/commit/2fd6e536f6bf83975ba09353a83e04d75e680535#comments).

Done. So either you merge #264 first, or you pick the same updates here.

**Comment by stweil** [comment]
Why was it necessary to downgrade Tesseract?

**Comment by kba** [comment]
> Why was it necessary to downgrade Tesseract?

https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/571/workflows/f9dbe858-91f7-41e6-b481-2d77595c1495/jobs/566 persistent segmentation faults when running `make ocrd-tesserocr-*-check`.

**Pull request merged**
