### PR TITLE
CircleCI: Replace legacy by next-gen convenience images

### PR DESCRIPTION
**Pull request by stweil**
See https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
Citing CircleCI: "They are designed to be faster, more efficient, and most importantly, more reliable."

Let's see whether that is true.

**Comment by kba** [comment]
> Let's see whether that is true.

There's always hope 🤞

**Comment by stweil** [comment]
As far as I can see CircleCI currently fails because of problems on our side. There is still an issue with `make -j`. Why are the Docker images build with that option? The CI environment only provides two CPUs, so `make -j2` might be a better choice.

**Comment by kba** [comment]
> Why are the Docker images build with that option? The CI environment only provides two CPUs, so make -j2 might be a better choice.

To prevent the context from timing out. I've written to the CircleCI support whether they can relax that limit, so we don't need all those optimizations to keep the build and deploy time under 1 hour.

**Comment by kba** [comment]
Let's try:

https://github.com/OCR-D/ocrd_all/compare/fix-ci / 
https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/747/workflows/95bc42a0-f31c-4da1-912a-a565b41eda9f/jobs/877

**Comment by stweil** [comment]
This PR should be merged.

**Comment by bertsky** [comment]
@stweil,
> There is still an issue with `make -j`. Why are the Docker images build with that option? The CI environment only provides two CPUs, so `make -j2` might be a better choice.

That's not true. We use `-j1`, sometimes `-j3` (we keep switching to either reach the timeout or avoid the race), but never `-j`.

> But it won't run faster if 50 jobs run in parallel on only two CPUs. `make -j2` should already be the best setting for that build environment. For faster builds we have to switch to a build environment with for example 4 CPUs.

Nothing of the kind would happen if you use `-j` (without further qualifiers). It would just use Loadlevel 1 (by default, unless set otherwise with `-l`), which means that an average of 100% of 1 core would be utilised. (But again, we don't actually use that setting.)

> I currently see no timeout failures, but only failures because of pip concurrency.

That's because if you enable concurrency, and the race condition hits into pip, you don't even get to the point of surviving 1h. If you disable it, then you can see the timeout. (See past CI runs.)

**Review by bertsky — APPROVED** [review]
It's worth a try. (See similar discussion of base image on ocrd_anybaseocr.)

**Comment by stweil** [comment]
@bertsky, my GitHub action fails to build the docker image:

```
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release' no longer has a Release file.
E: The repository 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release' no longer has a Release file.
```

What is causing this issue?

**Comment by bertsky** [comment]
> What is causing this issue? See also [full build log](https://github.com/stweil/ocrd_all/runs/5758316217).

No idea.

**Comment by stweil** [comment]
@kba, @bertsky, I'm afraid that building the Docker images with CUDA now has a fundamental problem. It looks like the NVIDIA base images at least for Ubuntu 18.04 no longer match to the apt sources which NVIDIA provides. That results in numerous missing Ubuntu packages which are related to CUDA. It is not even possible to run `apt update && apt upgrade`:

```
$ docker run -ti docker.io/nvidia/cuda:11.3.1-cudnn8-runtime-ubuntu18.04 /bin/bash
root@d1dc7a333112:/# apt update && apt upgrade
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease                 
Get:3 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]                                            
Ign:4 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Get:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [696 B]
Err:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
  404  Not Found [IP: 152.199.20.126 443]
Get:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                      
Get:9 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2672 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]      
Get:11 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [950 kB]
Get:12 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [869 kB]              
Get:13 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [21.1 kB]
Get:14 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1486 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]    
Get:16 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]         
Get:17 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2264 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3117 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [29.8 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [911 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [12.2 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [12.9 kB]
Reading package lists... Done                                 
E: The repository 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

When I try the same with the latest Docker image for Ubuntu 18.04, that also does not work:

```
$ docker run -ti docker.io/nvidia/cuda:11.6.0-runtime-ubuntu18.04 /bin/bash
root@8823ff5060bd:/# apt update
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                                                                        
Ign:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease                                                        
Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release [696 B]
Get:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Release.gpg [836 B]
Get:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [950 kB]  
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                          
Get:8 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                  
Get:9 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]    
Get:10 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2672 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]                     
Get:13 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]                                      
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3117 kB]                                   
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2264 kB]                               
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [911 kB]                             
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [29.8 kB]                           
Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [12.2 kB]                               
Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [12.9 kB]     
Get:20 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1486 kB]     
Get:21 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [21.1 kB]
Get:22 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [869 kB]
Fetched 25.7 MB in 2s (12.3 MB/s)                          
Reading package lists... Done
Building dependency tree       
Reading state information... Done
12 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@8823ff5060bd:/# apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  cuda-libraries-11-6 libcublas-11-6 libnccl2
The following packages will be upgraded:
  cuda-nvrtc-11-6 cuda-nvtx-11-6 libcufft-11-6 libcurand-11-6 libcusolver-11-6 libcusparse-11-6 libnpp-11-6 libnvjpeg-11-6 zlib1g
9 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Need to get 369 MB of archives.
After this operation, 23.6 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 zlib1g amd64 1:1.2.11.dfsg-0ubuntu2.1 [56.4 kB]
Err:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  cuda-nvrtc-11-6 11.6.124-1
  404  Not Found [IP: 152.199.20.126 443]
Err:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  cuda-nvtx-11-6 11.6.124-1
  404  Not Found [IP: 152.199.20.126 443]
Err:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  libcufft-11-6 10.7.2.124-1
  404  Not Found [IP: 152.199.20.126 443]
Err:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  libcurand-11-6 10.2.9.124-1
  404  Not Found [IP: 152.199.20.126 443]
Err:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  libcusolver-11-6 11.3.4.124-1
  404  Not Found [IP: 152.199.20.126 443]
Err:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  libcusparse-11-6 11.7.2.124-1
  404  Not Found [IP: 152.199.20.126 443]
Err:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  libnpp-11-6 11.6.3.124-1
  404  Not Found [IP: 152.199.20.126 443]
Err:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  libnvjpeg-11-6 11.6.2.124-1
  404  Not Found [IP: 152.199.20.126 443]
Fetched 56.4 kB in 4s (13.0 kB/s)
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./cuda-nvrtc-11-6_11.6.124-1_amd64.deb  404  Not Found [IP: 152.199.20.126 443]
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./cuda-nvtx-11-6_11.6.124-1_amd64.deb  404  Not Found [IP: 152.199.20.126 443]
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./libcufft-11-6_10.7.2.124-1_amd64.deb  404  Not Found [IP: 152.199.20.126 443]
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./libcurand-11-6_10.2.9.124-1_amd64.deb  404  Not Found [IP: 152.199.20.126 443]
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./libcusolver-11-6_11.3.4.124-1_amd64.deb  404  Not Found [IP: 152.199.20.126 443]
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./libcusparse-11-6_11.7.2.124-1_amd64.deb  404  Not Found [IP: 152.199.20.126 443]
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./libnpp-11-6_11.6.3.124-1_amd64.deb  404  Not Found [IP: 152.199.20.126 443]
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/./libnvjpeg-11-6_11.6.2.124-1_amd64.deb  404  Not Found [IP: 152.199.20.126 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by stweil** [comment]
See https://gitlab.com/nvidia/container-images/cuda/-/issues/152 for additional information on the currently broken `nvidia/cuda` container images.

**Pull request merged**
