### PR TITLE
update ocrd_kraken

### PR DESCRIPTION
**Pull request by bertsky**
Even if still PR, the newer ocrd_kraken is already usable and therefore should be re-activated.

(Note: will probably work even better after applying the [recent suggestions](https://github.com/OCR-D/ocrd_kraken/pull/33#pullrequestreview-886469286) and updating here again.)

### CODE REVIEW

**Comment by bertsky** [comment]
> Did you merge the fix in master back to this branch? I did for your
> PR #289 and it's running again.

I didn't know CI config is taken from the very branch it applies to.

CI failure: see [here](https://github.com/OCR-D/ocrd_kraken/pull/33#pullrequestreview-900803910)

**Comment by stweil** [comment]
What about https://github.com/OCR-D/ocrd_kraken/pull/33? I think we should require kraken 3.0.9 or even 4.0.

**Comment by stweil** [comment]
Maybe PR #297 which also touches the Makefile rules for `ocrd_kraken` can be integrated here, too (or applied after this PR to avoid a merge conflict here).

**Comment by bertsky** [comment]
@stweil,
> What about [OCR-D/ocrd_kraken#33](https://github.com/OCR-D/ocrd_kraken/pull/33)? I think we should require kraken 3.0.9 or even 4.0.

I don't understand your question. This PR sets ocrd_kraken to PR 33, which already requries `kraken>=3.0` in ocrd_all.

> Maybe PR #297 which also touches the Makefile rules for `ocrd_kraken` can be integrated here, too (or applied after this PR to avoid a merge conflict here).

No, it's the other way round. This PR is minimal and has been hanging here for one month already.

**Comment by stweil** [comment]
> No, it's the other way round. This PR is minimal and has been hanging here for one month already.

To bring it to the point: this PR breaks some build configurations which no longer work when it is applied. I only suggested to fix that before the PR is merged instead of first breaking and then fixing.

**Comment by bertsky** [comment]
> To bring it to the point: this PR breaks some build configurations which no longer work when it is applied. I only suggested to fix that before the PR is merged instead of first breaking and then fixing.

You mean Python 3.10? That can wait. Users should finally have ocrd_kraken back. Merging is on your side.

**Review by kba — APPROVED** [review]

**Pull request merged**
