### PR TITLE
core install: pass sem into every pip call

### PR DESCRIPTION
**Pull request by bertsky**

### CODE REVIEW

**Comment by stweil** [comment]
This conflicts with #299.

**Comment by bertsky** [comment]
> This conflicts with #299.

I don't care TBH – we are still trying to solve the deployment misery (see CI failures for CUDA variant and recent `-j` switching), which is urgent.

This is necessary to get a true separation of `pip` calls between (possibly parallel) venvs.

**Comment by kba** [comment]
> This conflicts with #299.

I think it's a counterargument to #299. And it seems to fix the issue at hand (race condition while installing core). Let's merge and hope for the best. If CD still fails, I will push the images manually.

**Comment by kba** [comment]
> > This conflicts with #299.
> 
> I think it's a counterargument to #299.

Wrong, sry. We still don't need $(PIP) in the ocrd_all Makefile, only in dependent packages.

**Comment by stweil** [comment]
I fixed the merge conflict in #299 (now for the second time), so it is ready for merging again.

**Pull request merged**
