### PR TITLE
Update 2021 04 23

### PR DESCRIPTION
**Pull request by kba**

### CODE REVIEW

**Comment by kba** [comment]
CI keeps failing because `make check` triggers SEGFAULT with ocrd_tesserocr - @stweil @bertsky any idea what this might be about? https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/534/workflows/de7f4786-ace0-4885-aff5-9d52b0b910bf/jobs/526

**Comment by bertsky** [comment]
What's the status of this PR @kba? You seem to have preponed the eynollah update in another PR, hence the conflict. Anyway, the CI failure you mention does not seem related to any of the changes here. Does it _not_ occur elsewhere?

(I just stumbled over this because I thought the new ocrd_anybaseocr has long been merged into ocrd/all ... could we factor this out?)

**Comment by kba** [comment]
> What's the status of this PR @kba? You seem to have preponed the eynollah update in another PR, hence the conflict. 

I abandoned it because I could not debug the segfaults.

> Anyway, the CI failure you mention does not seem related to any of the changes here. Does it _not_ occur elsewhere?

Not that I am aware of. 

> 
> (I just stumbled over this because I thought the new ocrd_anybaseocr has long been merged into ocrd/all ... could we factor this out?)

My bad, I missed ocrd_anybaseocr, I've added it to #256.

**Comment by bertsky** [comment]
> I abandoned it because I could not debug the segfaults.

ok

> Not that I am aware of.

let's pray then :crossed_fingers: 

> My bad, I missed ocrd_anybaseocr, I've added it to #256.

thx!

**Pull request closed without merging**
