### PR TITLE
Update ocrd_tesserocr

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
Should I add more updates (for example ocrd_fileformat) as well?

**Comment by kba** [comment]
> Should I add more updates (for example ocrd_fileformat) as well?

I'll make a new `./release.sh` run.

**Comment by kba** [comment]
@stweil AFAICS this PR is superseded by (merged) #185 and can be closed, right?

**Comment by stweil** [comment]
Yes, right.

**Pull request closed without merging**
