### PR TITLE
update 2023-03-16

### PR DESCRIPTION
**Pull request by kba**

### CODE REVIEW

**Comment by stweil** [comment]
I noticed yesterday that `make all` fails with Ubuntu 18.04 and any Python version, see [CI protocol](https://github.com/OCR-D/ocrd_all/actions/runs/4439490426/jobs/7792023575).  The CI jobs hang and always print the same message until they get canceled:
```
parallel: Warning: Semaphore stuck for 30 seconds. Consider using --semaphoretimeout.
```

**Comment by bertsky** [comment]
There seems to be a problem with that dinglehopper commit.

Also, [CI failure on master](https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/877/workflows/953e2bba-62e1-49f5-8b10-9cf9662ddcf3/jobs/1125) looks like we have to hold numpy for ocrd_keraslm. Just pushed [fix](https://github.com/OCR-D/ocrd_keraslm/commit/9c5047807277937cfe1d35b9cac95a82dd68fe95) there :crossed_fingers:

**Comment by kba** [comment]
Wow, GH closes a PR if you force-push the only commit and does not allow reopening. Not sure whether this is new behavior but it certainly is annoying.

> Is Ubuntu 18.04 still relevant, or should we remove it from CI now?

No, it is not and yes we should.

**Comment by kba** [comment]
Argh, my bad, I accidentally amended a commit that was in master m-(. Force-push and new PR incoming, sry about that.

**Comment by bertsky** [comment]
> Also, [CI failure on master](https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/877/workflows/953e2bba-62e1-49f5-8b10-9cf9662ddcf3/jobs/1125) looks like we have to hold numpy for ocrd_keraslm. Just pushed [fix](https://github.com/OCR-D/ocrd_keraslm/commit/9c5047807277937cfe1d35b9cac95a82dd68fe95) there


ah, of course we are screwed there: 
```
Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64

Starting container ocrd/core
...
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.15.* (from versions: 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.12.0)
```

**Comment by kba** [comment]
> There seems to be a problem with that dinglehopper commit.

Yeah, I was in the wrong branch, is now fixed.

> 18.04 is still used in CircleCI. Does that need a change, too? I can prepare a PR for the rest.

Yes, but unless that is a breaking issue now, let's do it after this update.

> And should Python 3.6 also be removed?

I'd say not right now, but in the next release?

**Pull request closed without merging**
