### PR TITLE
Module updates

### PR DESCRIPTION
**Pull request by kba**
ocrd: 2.1.0 -> 2.1.2
ocrd_olena: 1.0.0 -> 1.1.0
ocrd_im6convert: -> 0.0.2
opencv-python: minor setup.py fix
tesseract: minor fixes
workflow-configuration: allow making workspaces as explicit targets without installation

### CODE REVIEW

**Comment by stweil** [comment]
Is this PR ready for merging now?

**Comment by kba** [comment]
There's an issue with building workflow-configuration in circle ci, I'll have to look into before mergeing.

**Comment by bertsky** [comment]
> There's an issue with building workflow-configuration in circle ci, I'll have to look into before mergeing.

Sorry! Please update once more to fix this.

**Comment by kba** [comment]
Now let's see how the -git variants build in master 🤞

**Comment by kba** [comment]
Building -git variants works like a charm https://circleci.com/gh/OCR-D/ocrd_all/22 Takes about 1h50m to build and deploy but build and deploy it does.

**Pull request merged**
