### PR TITLE
Don't add opencv-python to OCRD_MODULES by default

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by kba** [comment]
Why do we need opencv-python as part of this at all?

**Comment by stweil** [comment]
Ideally `make all` works on any recent Linux, not only x86_64, but also ARM or Power64 based hosts which are interesting for OCR because of their included GPU or high memory bandwidth.

Currently there exist no pre-compiled Python packages `opencv-python` or `opencv-python-headless` for such non x86_64 hosts. So having the source at hand helps for a manual installation.

**Comment by kba** [comment]
> Currently there exist no pre-compiled Python packages opencv-python or opencv-python-headless for such non x86_64 hosts. So having the source at hand helps for a manual installation.

Just as I was asking, @wrznr complained that there are no debug builds for opencv-headless py36 on pypi. I retract my question :)

**Comment by kba** [comment]
I messed up merging this locally into #38 so your commit doesn't appear there. Sorry. But its contents are part of #38.

**Pull request merged**
