### PR TITLE
update 2024-06-08

### PR DESCRIPTION
**Pull request by kba**

### CODE REVIEW

**Comment by stweil** [comment]
I made a new Tesseract release yesterday. Maybe update ocrd_tesserocr to include it with some nice new features and code improvements.

**Comment by bertsky** [comment]
CI says:
```
Cloning into '/home/circleci/project/ocrd_fileformat'...
fatal: remote error: upload-pack: not our ref 048d924196a46654662660d4b0a0bfc4cdb8adb8
fatal: Fetched in submodule path 'ocrd_fileformat', but it did not contain 048d924196a46654662660d4b0a0bfc4cdb8adb8. Direct fetching of that commit failed.
```
And indeed, https://github.com/OCR-D/ocrd_fileformat/tree/048d924196a46654662660d4b0a0bfc4cdb8adb8 is not public. Perhaps something you forgot to push?

Also, could you please update workflow-configuration one more time?

And perhaps the changelog should include some of the rule changes from https://github.com/OCR-D/ocrd_all/pull/436 (notifying users about ocrd_kraken → sub-venv and ocrd_segment → top-venv in particular).

**Comment by bertsky** [comment]
That's odd – CI says build is "blocked", a [manual rerun](https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/1075/workflows/9846646e-c53e-419d-8429-402a49a2da44?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) shows as "not run" – what's going on?

**Comment by kba** [comment]
> PR [OCR-D/ocrd_tesserocr#214](https://github.com/OCR-D/ocrd_tesserocr/pull/214) updates ocrd_tesserocr. I suggest to merge it and use the updated submodule.

Argh, sry, saw this too late, will do.

**Pull request merged**
