### PR TITLE
update submodules (avoiding TF 1 vs 2 conflict)

### PR DESCRIPTION
**Pull request by bertsky**
This brings updates to ocrd_keraslm and cor-asv-ann which will completely avoid conflict with TF2 ocrd_anybaseocr – as a temporary solution to #69.

### CODE REVIEW

**Comment by stweil** [comment]
@bertsky, recent Linux distributions with Python 3.8 might all fail with `make all`:

    ERROR: No matching distribution found for tensorflow-gpu==1.15.* (from ocrd-cor-asv-ann==0.1.2)

I use Debian Bullseye (=testing) with Python 3.8.2.

**Comment by bertsky** [comment]
> all recent Linux distributions with Python 3.8 might fail with `make all`:
> 
> ```
> ERROR: No matching distribution found for tensorflow-gpu==1.15.* (from ocrd-cor-asv-ann==0.1.2)
> ```
> 
> I use Debian Bullseye (=testing) with Python 3.8.2.

Gosh, these TF people drive me crazy. First they just redefine their naming scheme **twice** for the same versions (`tensorflow` vs `tensorflow-gpu` on pre-2), then they don't even provide up-to-date builds anymore.

But you have to concede, they say so directly on their website:

> TensorFlow is tested and supported on the following 64-bit systems:
> 
> Python 3.5–3.7

And the [way they say it](https://github.com/tensorflow/tensorflow/issues/33838#issuecomment-566342226), it sounds they *will* provide 3.8 support...

**Comment by stweil** [comment]
We have several ways how to handle this:
- Do nothing. It will be solved as soon as there is a TF binary for Python 3.8.
- Do nothing. It only affects people who use the latest distributions. Those people should know how to handle problems.
- Add documentation to the README and hope that people read it.
- Enhance the Makefile to check the Python version. Fail with an error message if it is 3.8, or look whether there is also a Python 3.6 or 3.7 available and use that.
- ...

**Comment by kba** [comment]
I'm for a combination of "Do nothing" and a warning for python 3.8 users in the README. It's imperative for TF to provide up-to-date versions, supporting 3.8 must be high on their priorities and users that are on bleeding edge distros like Debian 11 or Ubuntu 20.04 can be expected to check the documentation or even install an older python in case of problems.

**Comment by bertsky** [comment]
On the other hand, we don't even look for Python 3.8 support in core ourselves yet (CircleCI and Travis use 3.5-3.7). That's not "3.5 or higher"...

**Pull request merged**
