### PR TITLE
update 2023-01-20

### PR DESCRIPTION
**Pull request by kba**
Fixes to core and ocrd_detectron2, new release of ocrd_olahd_client and updates to opencv and tesseract.

### CODE REVIEW

**Comment by kba** [comment]
PR is now [released](https://github.com/OCR-D/ocrd_all/releases/tag/v2023-02-06), I accidentally rebased while merging so the PR isn't automatically closed, doing it manually now.

**Comment by bertsky** [comment]
Note: the CI [failure](https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/871/workflows/ff0c5657-aa1b-4a58-86aa-ac9b60dacf59) after the merge was due to some downtime on the Ubuntu repository servers. I triggered a re-run :crossed_fingers:

**Comment by bertsky** [comment]
Ok, seems like we need the increased output timeout for builds on the other workflow, too. I commited the cfg change, let's see :crossed_fingers:

**Comment by kba** [comment]
Looks like it is passing now, thanks @bertsky

**Pull request closed without merging**
